### ISSUE TITLE
A11y

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/sharing#11]
- [x] Add ~~title~~ _aria-label_ attributes to buttons. (See here: https://www.nczonline.net/blog/2013/04/01/making-accessible-icon-buttons/) 
  More ideas how to improve accessibility?

**Comment by swastik** [comment]
You could possibly use something like http://www.508checker.com/index.php or http://achecker.ca/checker/index.php. Maybe add a `aria-role` attribute to the buttons?
