### ISSUE TITLE
Between 700px and 850px width, the radio-bullet is mispositioned

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/sharing#21]
On layouts smaller than 850px and before the mobile layout kicks in at 700px, the radio button bullet is wrongly positioned.

![screen shot 2015-12-02 at 10 13 35](https://cloud.githubusercontent.com/assets/7525670/11526838/8a4bc912-98dd-11e5-8c11-db1d627a8352.png)

**Comment by KimberleyCook** [comment]
@mxstbr is this issue still available? Would love to add it our list for our event on Saturday.

p.s thanks for sharing the repo with us :)

**Comment by mxstbr** [comment]
This has been fixed already I'm afraid, sorry for getting your hopes up! Forgot to close the issue 😊
