### ISSUE TITLE
Google+ no preview

### ISSUE THREAD

**Issue by lordspace** [mxstbr/sharing#25]
Thanks for the cool project.

I just included your project on my super recently released project (half an hour ago to be precise) http://wpdemoserver.com/

When sharing on Google+ there's no preview.

![screenshot 2016-01-21 02 47 51](https://cloud.githubusercontent.com/assets/137558/12468114/7edcd8a4-bfe9-11e5-8369-fbd680b96243.png)

**Comment by mxstbr** [comment]
Interesting, thanks for noticing that, I'll take a look!

**Comment by mxstbr** [comment]
Should be fixed now, please try again!

**Comment by lordspace** [comment]
What do I update?
HTML snippets?

**Comment by mxstbr** [comment]
Oh sorry, I misunderstood what you were saying, I thought you were sharing sharingbuttons.io on Google+, my bad! Reopening as this isn't fixed, let me take a deeper look!

**Comment by lordspace** [comment]
thanks!

**Comment by mxstbr** [comment]
I researched a bit, it turns out the Preview simply doesn't show, but will be posted. This happens with all G+ share links, so it isn't my fault and I can't fix that!

Thanks for reporting this bug!

<img width="551" alt="screen shot 2016-01-23 at 08 59 34" src="https://cloud.githubusercontent.com/assets/7525670/12529483/d9763a86-c1af-11e5-8e0b-090e82106e74.png">

**Comment by lordspace** [comment]
Can you try it on my site? 
http://wpdemoserver.com/ and then click on Google plus.
There's no description.
There's no thumbnail so I don't expect a thumbnail.

**Comment by mxstbr** [comment]
Sorry, but that's not on me, I have no influence over that. You probably don't have your `meta` tags configured correctly!

**Comment by lordspace** [comment]
I know but which tags? could it be the og: tags which are facebook related?

**Comment by mxstbr** [comment]
I think Google+ uses [schema.org](schema.org), but be sure to do a quick search and double check that!
