### ISSUE TITLE
Pinterest working?

### ISSUE THREAD

**Issue by sporkman** [mxstbr/sharing#28]
Not able to successfully share an image with the Pinterest button.  Not a user of the service, so I'm not sure of the details, but perhaps something has changed in how sharing works.  Generated url from sharingbuttons.io is this:  https://www.pinterest.com/pin/create/button/?url=http%3A%2F%2Fanneklein.com%2Fak-content%2Fuploads%2F2016%2F02%2Fak-color-front.jpg&summary=Super%20fast%20and%20easy%20Social%20Media%20Sharing%20Buttons.%20No%20JavaScript.%20No%20tracking.

Attached is a screenshot of the Pinterest error.
![screen shot 2016-08-01 at 1 19 10 pm](https://cloud.githubusercontent.com/assets/510750/17302537/b10b09ba-57ea-11e6-991f-6f75ed9fc658.png)

**Comment by mxstbr** [comment]
Oh no, that sounds like they changed the format! Will look into it, thanks!

**Comment by mxstbr** [comment]
Found the issue, Pinterest now forces us to specify an image or it'll fail. If the link is an image it works as expected again! (as soon as I've deployed, that is)
