### ISSUE TITLE
Add Hacker News

### ISSUE THREAD

**Issue by michaelmior** [mxstbr/sharing#30]
Would be awesome to add Hacker News as an option. Sharing link is in the format below

`https://news.ycombinator.com/submitlink?u=URL&t=TITLE`

**Comment by mxstbr** [comment]
Do you know of any good SVG icons for Hacker News in all four variations? (solid, circle, solid-circle, empty square)

**Comment by michaelmior** [comment]
I don't, but [gilbarbara/logos](https://github.com/gilbarbara/logos) has a [Y Combinator logo](https://github.com/gilbarbara/logos/blob/master/logos/ycombinator.svg).

**Comment by sotojuan** [comment]
^ If that looks good I can make a PR for this 😎

**Comment by mxstbr** [comment]
Sure, please do @sotojuan, I'd love that!

**Comment by twinlensreflex** [comment]
hi! we are picking this up at the codebar 24PullRequests event

**Comment by sotojuan** [comment]
Please do, I forgot about doing this (as I often do 😢).

**Comment by twinlensreflex** [comment]
@sotojuan no problem, submitted a pull request now 👯 👍
