### ISSUE TITLE
mailto: links should not open in a new window.

### ISSUE THREAD

**Issue by ndbroadbent** [mxstbr/sharing#32]
It opens a new empty web browser tab even when the links are handled by the OS (e.g. native mail client).

**Comment by billyquick** [comment]
Hey @ndbroadbent, what web browsers have you tried using? Some browsers support defaulting pop-up windows to open a new tab and some do not.

**Comment by ndbroadbent** [comment]
Hi, this happens for me on OS X when I use Chrome. The native Mail app opens to write a new email, but then I still have a blank tab open with the `mailto:` URL in the address bar, and the title: "Untitled".

I think removing the `target="_blank"` should be fine for all cases, any browser will always open a new window or popup by itself.

**Comment by billyquick** [comment]
I see. I agree, that seems like it should work.

**Comment by XhmikosR** [comment]
Duplicate of #26.

**Comment by mxstbr** [comment]
Thanks @XhmikosR, also fixed thanks to @pavelkomiagin in #36! 🎉
