### ISSUE TITLE
Minor Tweaks to Large/Medium Layouts

### ISSUE THREAD

**Issue by xpose2000** [mxstbr/sharing#33]
## Large Layout

Instead of "[icon] Share on Twitter" it should just say "[icon] Twitter".
## Medium Layout

Instead of "Twitter" it should say "[icon] Twitter".
## Get Rid of Large/Medium?

Infact, I think medium and large should merge to "normal".  Then "small" should have its own layout with just the icons.

**Comment by mxstbr** [comment]
I'm not convinced merging them is the right way to go, I do agree that `[icon] Twitter` is nicer for medium though! Why not this?
- Large: `[icon] Share on Twitter`
- Medium: `[icon] Twitter`
- Small: `[icon]`

**Comment by xpose2000** [comment]
Sure, that sounds like it'd most certainly work :)

**Comment by mxstbr** [comment]
Done by the amazing @lbntly in #43! 🎉
