### ISSUE TITLE
Adding Whatsapp share

### ISSUE THREAD

**Issue by OGPoyraz** [mxstbr/sharing#34]
Hey mxstbr, thanks for sharing a nice solution. It would be nice if you add Whatsapp too.

**Comment by mxstbr** [comment]
Does WhatsApp have a sharing link? Do you have any idea what their structure is?

**Comment by OGPoyraz** [comment]
Well, ofc it works on devices which have whatsapp. [Their FAQ about this](https://www.whatsapp.com/faq/en/android/28000012)

**Comment by mxstbr** [comment]
Oooh amazing! PR would be very welcome!

**Comment by mxstbr** [comment]
Done by the amazing @OGPoyraz in #42! 🎉
