### ISSUE TITLE
Website not loading in Safari using private mode

### ISSUE THREAD

**Issue by hagenburger** [mxstbr/sharing#35]
Safari’s private mode does not support `localStorage` and breaks with:

```
setItem — bundle.js:3832:106
QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
```

Result: You’ll see the loading spinner (actually first I thought this might be a website against using any sharing buttons, but then I had a second look)

Maybe at least catch this error and display a notification to load it without using the private mode?

**Comment by mxstbr** [comment]
Oooh that's horrible, I did NOT know that, sorry! We can just not store to localStorage if it doesn't exist, it's only there to persist the chosen options between visits – would you mind submitting a PR for that?

**Comment by mxstbr** [comment]
Will be fixed the next time I deploy thanks to the amazing @matter3!
