### ISSUE TITLE
Nearly impossible to select generated code

### ISSUE THREAD

**Issue by PickJBennett** [mxstbr/sharing#37]
### Description

Because the generated code uses DOM elements to highlight the syntax and not a <textarea>, selecting this code is extremely difficult on touch-screen devices.
### Steps to reproduce
1. Open (http://sharingbuttons.io/) in Mobile Safari on iOS 9.3.3
2. Generate code and try to select text with one finger while scrolling the highlighted syntax with the other.

**Expected behavior:** I expected the entire output to be selected on focus or at least be selectable.

**Actual behavior:** Extreme difficulty selecting generated code.

**Link to an example:** (http://sharingbuttons.io/)
### Versions
- Browser: Mobile Safari
- OS: iOS 9.3.3 on iPhone 6+

**Comment by olets** [comment]
Sorry you're having trouble! Haven't test on Android, but the (admittedly touchy) standard iOS method works for me:
- long click (selects one word)
- drag the "start of selection" handle up and over towards the left margin of the column

Last time I looked (and it has been a while) scripted solutions for selecting large blocks of text on mobile were unreliable, so we'll probably stick to mobile OSes' default methods. That said, if you have a better method go ahead and make a PR!
