### ISSUE TITLE
add Telegram sharing button

### ISSUE THREAD

**Issue by hadifarnoud** [mxstbr/sharing#45]
Telegram is a popular messaging app in Iran, Russia, and Arab countries. Please add Telegram too.

http://telegram.wiki/tips:websharing

**Comment by mxstbr** [comment]
Absolutely, I use it too! If you have any idea where we can find icons I'm sure we can look into it :+1:

**Comment by hadifarnoud** [comment]
there are loads of icons for Telegram. how about [this one](http://www.flaticon.com/free-icon/telegram-logo_87413)?

**Comment by hadifarnoud** [comment]
this is nice too: http://www.easyicon.net/language.en/1145402-telegram_icon.html

**Comment by xoniq** [comment]
https://www.iconfinder.com/search/?type=vector&price=free&q=telegram

**Comment by olets** [comment]
Let's use the "arrowhead" silhouette from https://commons.wikimedia.org/wiki/File:Telegram_alternative_logo.svg - it's one of their official icons (see the banner in the OP's link), and it matches sharingbutton.io's other icons
