### ISSUE TITLE
Add VK.com

### ISSUE THREAD

**Issue by lolmaus** [mxstbr/sharing#46]
VK (old name VKontakte, "in contact") is a very active social network of Russian origin, it's audience size is [~5%](http://www.statista.com/statistics/272014/global-social-networks-ranked-by-number-of-users/) of that of Facebook, which is still incredibly huge.

![image](https://cloud.githubusercontent.com/assets/200884/17461540/2174aa78-5c99-11e6-8bd8-b4b89d5f6f79.png)

API docs: https://new.vk.com/dev/share_details

**Comment by olets** [comment]
@mxstbr do you want to limit networks to international ones?

@lolmaus check the contribution notes here https://github.com/mxstbr/sharingbuttons.io/wiki

**Comment by mxstbr** [comment]
I'm fine with VK since it's huge, I think we could just not enable it by default?

(Also, that contribution guide is awesome! Thanks!)
