### ISSUE TITLE
optimize svgs

### ISSUE THREAD

**Issue by olets** [mxstbr/sharing#51]
The svgs could be optimized. My favorite tool for this is https://jakearchibald.github.io/svgomg/. I use precision:1 or precision:2 (check each svg, and use precision:1 if it still looks good), and turn on all features except for "remove viewBox." Because `width` and `height` are removed, they must be added back in the css (like `.resp-sharing-button__icon svg {width: 24px; height:24px}`)

For example, I tested logo-circle-pinterest.svg. I used SVGOMG with precision:2 (looked the same as the original) and the size dropped 19%. Then I removed the `stroke-miterlimit` and `stroke-linejoin` (these are not really necessary, but SVGOMG does not remove them). Delete the `fill` and `stroke` - they can be in css. The result is 579b, down 30% from the original.

Of course, 300b is not a lot. But it is easy to do, and then you know your icons are the smallest possible!

**Comment by mxstbr** [comment]
Sounds really good, would love a PR!

**Comment by olets** [comment]
Life got all busy, but this is near the top of my to-do list!

**Comment by olets** [comment]
Done at last! ^

**Comment by mxstbr** [comment]
Awesome!
