### ISSUE TITLE
Add FB Messenger send

### ISSUE THREAD

**Issue by gojeg** [mxstbr/sharing#54]
Hi, FB has e Send button for its Messenger. It would be great if you add this feature to the sharing buttons. Thanks.

https://developers.facebook.com/docs/plugins/send-button

**Comment by olets** [comment]
The send button solution won't work here, but good news: the current Facebook link supports sending the link in a direct Fb message: 

<img src="https://cloud.githubusercontent.com/assets/3282350/17752226/d5ad957a-6498-11e6-97f4-5d2eb2d29ae5.png" width="200px"/>
