### ISSUE TITLE
A bit more space between buttons

### ISSUE THREAD

**Issue by mrnagy88** [mxstbr/sharing#57]
I updated the margin on my css version but a bit more space between buttons would do good on SEO/mobile friendliness tests for tap targets for the small button size.

I think they recommend minimum 8 or 10 pixels space between buttons on mobile right?

I could be wrong, the issue might be the size of the buttons themselves but I like the small ones.

Love this tool btw!

**Comment by equinusocio** [comment]
Just edit the provided css or use your own classes.

**Comment by olets** [comment]
Google's PageSpeed Insights recommends primary tap targets be at least 7mm x 7mm (approx. 48 css pixels), with 5mm space (32 css pixels) separating them from other tap targets.<sup>1</sup>.

The buttons are currently 20px tall separated 16px. @mrnagy88 this isn't going to impact SEO, at least with Google

> Technically speaking, Google does not use the PageSpeed Insights tool to determine search engine ranking (but may do in the future).

but if we take their recommendation to heart it could be good to make the tap targets bigger and more spaced out on mobile with a `@media` query. The larger tap target could be a larger visible button, or adding (transparent, clickable) padding to the links, or (my intuition is this would be best) a little of both. Submit a PR?

<sup>1</sup> https://developers.google.com/speed/docs/insights/SizeTapTargetsAppropriately

**Comment by mrnagy88** [comment]
I'm not sure but I got an error in an SEO report, I suspect it might be the little dashes that appear when you hover that is creating the error message then, or the way I had it set up on my page perhaps with other links nearby. Have you seen those hidden dashes?

Here is an example with the dashes:
http://www.cosmoscondovip.ca/
When you include that invisible tap target space the links are essentially touching

I see now it's a CSS underline that's set on all `<a>` links on my page only. Still are the tap targets supposed to touch like that?
