### ISSUE TITLE
Missing Facebook and Google+ buttons

### ISSUE THREAD

**Issue by gabll** [mxstbr/sharing#58]
Can't see anymore the buttons for Facebook and Google+ if selected

**Comment by mxstbr** [comment]
Not sure what you mean, I can still see both of them. Do a hard refresh maybe?

<img width="987" alt="screen shot 2016-08-23 at 21 15 57" src="https://cloud.githubusercontent.com/assets/7525670/17890044/d6f9d7bc-6976-11e6-9e2f-b48ead075bd3.png">

**Comment by gabll** [comment]
Ok, they doesn't work only if Adblock Plus for chrome is enabled. Sorry

![image](https://cloud.githubusercontent.com/assets/10371551/17890991/981d5560-6939-11e6-84fe-659a88f72ddc.png)

**Comment by mxstbr** [comment]
Huh, that's weird! I wonder how they block those…
