### ISSUE TITLE
The icons in the preview are too small

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/sharing#6]
![screen shot 2015-11-29 at 15 00 26](https://cloud.githubusercontent.com/assets/7525670/11457448/fc9bd2ea-96a9-11e5-8a49-db93d499fa40.png)

**Comment by andrunix** [comment]
Hello. I am fixing this bug but I wasn't sure how you generate the app.css from the scss files. I'll be happy to add that to the README also if you can give me the command to generate the app.css. Thanks. :)

**Comment by mxstbr** [comment]
@andrunix Thanks so much for checking it out!

I just changed the entire setup of the app because I refactored a lot of the code. If you `git pull` again, the code for the preview buttons is in `css/modules/_generator-preview.css`, and the command to generate the CSS is simply `npm start`. When you change something in the CSS with `npm start` running, the website should automatically refresh and show the newest CSS!

Cheers!
