### ISSUE TITLE
Add onClick with popup

### ISSUE THREAD

**Issue by equinusocio** [mxstbr/sharing#60]
Allow onClick popup instead to open the link in the current window. This help to maintain the focus and allows multiple actions at the same time.

[DEMO](https://jsfiddle.net/equinusocio/qzohnvc6/)

``` html
<a class="resp-sharing-button__link"
   href="https://facebook.com/sharer/sharer.php?u=http%3A%2F%2Fsharingbuttons.io"
   target="_blank"
   aria-label="Facebook"
   onclick="window.open(this.href,'','scrollbars=yes,menubar=no,width=700,height=600,resizable=yes,toolbar=no,location=no,status=no');
 return false;">
```

**Comment by olets** [comment]
Nice idea. In another project I already have window dimensions for some of the pop-ups we'll need. I'll add those in the next couple days, and then we can see what services are still missing

**Comment by mxstbr** [comment]
Sounds awesome, let's make this optional though! (toggle on/off)

**Comment by equinusocio** [comment]
Obviously `target="_blank"` is useless when there is the `onClick` attribute. 👍

**Comment by mxstbr** [comment]
That'd be a fallback though, if JS is disabled, right?

**Comment by peter-mouland** [comment]
*or if the user clicks before the js had fully initialised i.e. slow connection/device

**Comment by equinusocio** [comment]
@peter-mouland It's a native js string, not jQuery :P. I think the `onClick` can be launched before the html appear 😂

**Comment by peter-mouland** [comment]
lol - ah yeah, was thinking of js event rather than html! i'll go back to sleep! 😴

**Comment by equinusocio** [comment]
What is "Hacktoberfest" tag? This is not hack.

**Comment by equinusocio** [comment]
@olets Any update?

**Comment by mxstbr** [comment]
> What is "Hacktoberfest" tag? This is not hack.

See [here](https://hacktoberfest.digitalocean.com).

**Comment by equinusocio** [comment]
Ok, so we have to wait 1 year for this enhancement? .... .. .

**Comment by mxstbr** [comment]
No, just submit a PR if you want to :blush:

**Comment by sparr** [comment]
Why onClick instead of just target?
