### ISSUE TITLE
Whatsapp icon is all white in solid circle mode

### ISSUE THREAD

**Issue by siddharthkp** [mxstbr/sharing#63]
Check out this share button - The whatsapp icon is all white.

<img width="253" alt="screen shot 2016-09-22 at 8 54 12 pm" src="https://cloud.githubusercontent.com/assets/1863771/18754586/cf48feba-8106-11e6-86d8-180e31b3472d.png">

This is because the whatsapp logo has white instead of transparent. Compare it with the twitter logo.

<img width="166" alt="screen shot 2016-09-22 at 8 59 44 pm" src="https://cloud.githubusercontent.com/assets/1863771/18754792/91e2300e-8107-11e6-9ccd-51cf1e2c8964.png"> <img width="161" alt="screen shot 2016-09-22 at 9 00 01 pm" src="https://cloud.githubusercontent.com/assets/1863771/18754791/9103abfe-8107-11e6-9dc5-219002df784d.png">

Digging deeper, it seems the way it is structured. The whatsapp logo has an extra white path on it.

<img width="387" alt="screen shot 2016-09-22 at 9 05 07 pm" src="https://cloud.githubusercontent.com/assets/1863771/18755065/601d2348-8108-11e6-876a-9d50472ddce1.png"> <img width="393" alt="screen shot 2016-09-22 at 9 05 38 pm" src="https://cloud.githubusercontent.com/assets/1863771/18755067/6146ec4a-8108-11e6-9148-2a429ae46e9e.png">

There are two things I can think of - 
1. Make another svg which only is only made of black strokes leaving the icon in transparent. (Sorry, I can't help you with that)
2. Use a png instead.

@mxstbr, What do you think?

**Comment by mxstbr** [comment]
Definitely want to stick with SVG, I'd much rather edit the SVG to make this work. Not an expert myself though.

(@una mentioned on Twitter about looking for open source projects to contribute to, this might be a good first bug?)

**Comment by siddharthkp** [comment]
@mxsbtr, that's how I landed here :smile:
Not sure if this is a beginner's bug though, you need some svg wizardry

**Comment by siddharthkp** [comment]
But, maybe I can source it from somewhere. Self assigning.
