### ISSUE TITLE
Pinterest button not working for my sites

### ISSUE THREAD

**Issue by mrnagy88** [mxstbr/sharing#66]
Not sure if this is pinterest or something with the buttons:

2 of my sites with the button;
https://www.kingswayriver.ca/
http://www.mypandacondos.ca/

I didn't modify the HTML output only the CSS so not sure what's causing it, perhaps something in the description or a change in Pinterest's required variables?

On my chrome it doesn't bring up the image selection, on another PC it brought it up, but couldn't find any images.

Thanks!
Daniel

**Comment by mrnagy88** [comment]
In both cases we were already logged in to Pinterest, not sure if that has an affect.

**Comment by mrnagy88** [comment]
Probably relates to these or can give us clue on the proper format:
http://assets.pinterest.com/js/pinit.js
http://assets.pinterest.com/js/pinit_main.js

**Comment by lucahammer** [comment]
Had the same issue. Found the problem. Pinterest expects a parameter 'description=', but sharingbuttons.io generates a parameter 'summary='.

This doesn't work:
```
<!-- Sharingbutton Pinterest -->
<a class="resp-sharing-button__link" href="https://pinterest.com/pin/create/button/?url=http%3A%2F%2Fsharingbuttons.io&amp;media=http%3A%2F%2Fsharingbuttons.io&amp;summary=Super%20fast%20and%20easy%20Social%20Media%20Sharing%20Buttons.%20No%20JavaScript.%20No%20tracking." target="_blank" aria-label="Share on Pinterest">
```


This works:
```
<!-- Sharingbutton Pinterest -->
<a class="resp-sharing-button__link" href="https://pinterest.com/pin/create/button/?url=http%3A%2F%2Fsharingbuttons.io&amp;media=http%3A%2F%2Fsharingbuttons.io&amp;description=Super%20fast%20and%20easy%20Social%20Media%20Sharing%20Buttons.%20No%20JavaScript.%20No%20tracking." target="_blank" aria-label="Share on Pinterest">
```


I tried to write a pull request, but failed to find the appropriate section in the code. Some day I will learn react.

**Comment by mxstbr** [comment]
Well, you found it after all! Thanks for digging in @lucahammer, this should work now: http://sharingbuttons.io!
