### ISSUE TITLE
sharingbuttons.io down

### ISSUE THREAD

**Issue by cedricdelpoux** [mxstbr/sharing#83]
Hi, 

When I go on [sharingbuttons.io](http://sharingbuttons.io/), I have this error on a blank screen:

```
TypeError: Path must be a string. Received undefined
```

**Comment by blairanderson** [comment]
mirror: https://www.blairanderson.co/sharingbuttons/
screenshot:
![screen shot 2017-07-21 at 10 43 08 am](https://user-images.githubusercontent.com/955736/28475515-6ec53aac-6e01-11e7-8be9-e4ffde9acbb9.png)

did the CNAME file get removed?

**Comment by Naereen** [comment]
@mxstbr Any new on that?

**Comment by mrnagy88** [comment]
Is it possible for anyone to mirror this site temporarily given the code is available here? I wouldn't know how to set it up or else I would add a copy myself.

**Comment by blairanderson** [comment]
this site was built with reactv12 and current is v16. 

Lot has changed since then in node/webpack/react/etc.  

@mxstbr would you recommend someone fire up a new create-react-app and copy stuff over?

**Comment by blairanderson** [comment]
# mirron hosted on github pages: https://www.blairanderson.co/sharingbuttons/

**Comment by mrnagy88** [comment]
Thanks Blairanderson I really appreciate that, I had started to install offline webserver programs to host it locally but I didn't get through the install this saves a lot of time for our web dev team ;-)

Daniel

**Comment by tobiastornros** [comment]
sharingbuttons.io works for me.

**Comment by mxstbr** [comment]
Sorry for the troubles! I fixed it a couple of weeks ago, if you're still seeing it being down do a hard-refresh!

Thanks for the temporary mirror @blairanderson.

**Comment by Naereen** [comment]
Great, it works for me. :+1:
