### ISSUE TITLE
Have the logos be a sprite or font-based

### ISSUE THREAD

**Issue by bfad** [mxstbr/sharing#84]
I think it would be beneficial to have the logos be in a single sprite image or a single font. It would add an extra HTTP request, but at least it would be cacheable. Subsequent requests wouldn't have to make the additional request, and since the SVG code isn't inline, that means a reduction in bandwidth on those requests as well.

**Comment by bfad** [comment]
Or, maybe move the SVG data into a CSS `background-image: url("data:image/svg+xml;...)` since the CSS will be cached?

**Comment by sparr** [comment]
Is this still relevant? SVG appears to be inline now.

**Comment by mxstbr** [comment]
I think this is out of the scope of this project, as it is a small enhancement that might or might not work out as a benefit when tested with your actual production users. Will close this for now, thanks for starting this discussion @bfad!
